### ISSUE TITLE
ACK/NACK message id parsing in STOMP 1.2

### ISSUE THREAD

**Issue by samavedulark** [rabbitmq/rabbitmq-stomp#10]
I am getting issues while calling NACK/ACK. 
Below are the sequence of messages. Correct me if i am doing anything wrong.
I am using from Spring Websockets.

```
CONNECT
accept-version:1.2,1.1
--------------------------
CONNECTED
server:RabbitMQ/3.3.5
heart-beat:0,0
version:1.2
session:session-LqaSmsWbsrq4y1EkEDS
-----------------------------------------
SUBSCRIBE
destination:/queue/test123
ack:client-individual
id:141414
----------------------------------------------
MESSAGE
content-length:6
destination:/queue/test123
ack:T_141414@@session-LqaSmsWbsrq4y1EkEDS4RQ@@1
message-id:T_141414@@session-LqaSmsWbsrq4y1EkEDS4RQ@@1
subscription:141414
persistent:1
content-length:6

Hello
-------------------------------------------------

NACK
requeue:False
message-id:T_141414@@session-LqaSmsWbsrq4y1EkEDS4RQ@@1
subscription:141414
id:141414
-----------------------------------------------------
ERROR
content-length:40
content-type:text/plain
message:Invalid header
version:1.0,1.1,1.2
content-length:40

"NACK" must include a valid "id" header
```

**Comment by michaelklishin** [comment]
Interesting. The ack ID header has changed between STOMP 1.1 and 1.2 (from `message-id` to `id`) and thus has different format.

Can you try explicitly setting version to 1.1?

**Comment by michaelklishin** [comment]
* [STOMP 1.1](https://stomp.github.io/stomp-specification-1.1.html#ACK)
* [STOMP 1.2](https://stomp.github.io/stomp-specification-1.2.html#ACK)

The plugin picks the correct header but parsing seems to imply the 1.0-1.1 format.

**Comment by samavedulark** [comment]
Hi, 

For STOMP 1.1, it is ACK is working.
But for NACK

NACK
requeue:False
message-id:T_141414@@session-fOKKNpEzFcT0oYuoDjIXfw@@1
subscription:141414

It is keep on sending the message to my client.

**Comment by michaelklishin** [comment]
@samavedulark that's because you need to add one more header to void the message: `requeue: false`. I'm curious if that should be the default :/

**Comment by michaelklishin** [comment]
I see that the `requeue` header is mentioned [in the documentation](http://www.rabbitmq.com/stomp.html):

```
NACK frames can optionally carry the requeue header which controls whether the message will be requeued or discarded/dead lettered. Default value is true.
```

**Comment by samavedulark** [comment]
But "reuque:False" is present in the header.

NACK
requeue:False
message-id:T_141414@@session-fOKKNpEzFcT0oYuoDjIXfw@@1
subscription:141414

**Comment by michaelklishin** [comment]
@samavedulark 
1. you have it capitalized
2. If it an issue, it is completely unrelated

**Comment by samavedulark** [comment]
No, i have tried both.
requeue:false & requeue:False.
Still getting messages.

**Comment by michaelklishin** [comment]
@samavedulark fine, I'll file another issue to investigate. Thank you for reporting this STOMP 1.2 behaviour change.

**Comment by samavedulark** [comment]
Thanks So much, it was very helpful.

**Comment by michaelklishin** [comment]
@samavedulark can you please post some code that demonstrates what you do?

The 1.2 spec [says](https://stomp.github.io/stomp-specification-1.2.html#ACK)

```
The ACK frame MUST include an id header matching the ack header of the MESSAGE being acknowledged.
```

and some clients forcefully set the same value for both. I'd like to give the same client you use a try as it may be a client issue just as much as it is something RabbitMQ could cope better with.

**Comment by samavedulark** [comment]
Message is same as above.
NACK
requeue:False
message-id:T_141414@@session-LqaSmsWbsrq4y1EkEDS4RQ@@1
subscription:141414
id:141414

**Comment by michaelklishin** [comment]
@samavedulark thanks, I was talking about your Spring Websocket code.

**Comment by samavedulark** [comment]
@Override
	public void configureMessageBroker(MessageBrokerRegistry config) {
		config.enableStompBrokerRelay("/topic/","/queue/","/exchange/").setRelayHost(amqpServiceInfo.getHost()).setSystemLogin("user1")
		.setSystemPasscode("password")
		.setClientLogin("user1").setClientPasscode("password");
}

@Override
	public void registerStompEndpoints(StompEndpointRegistry registry) {
		registry.addEndpoint("/test123");
	}

	@Override
	public void configureWebSocketTransport(
			WebSocketTransportRegistration registry) {
		registry.setSendBufferSizeLimit(128 * 1024 * 1024);
		
	}

	@Override
	public void configureClientInboundChannel(ChannelRegistration registration) {
		registration.taskExecutor().maxPoolSize(50);
		
	}

	@Override
	public void configureClientOutboundChannel(ChannelRegistration registration) {
		registration.taskExecutor().maxPoolSize(50);
	}

**Comment by dumbbell** [comment]
Hi @samavedulark!

About the `id` header, the client sent an incorrect ID in the `ACK` frame. The STOMP 1.2 specification states that the `ACK`'s (or `NACK`'s) `id` header must have the same value as `MESSAGE`'s `ack` header. However, in the trace you posted, the `id` is set to the subscription ID instead:

```
MESSAGE
...
ack:T_141414@@session-LqaSmsWbsrq4y1EkEDS4RQ@@1
```
```
NACK
...
id:141414
```

**Comment by michaelklishin** [comment]
@dumbbell this is something we should report to the Spring team.

**Comment by dumbbell** [comment]
I'm not sure where this should be reported; Spring Framework?

@samavedulark, what do you suggest? Or better, could you please report the problem to the relevant project? :-)

**Comment by michaelklishin** [comment]
@dumbbell looks like [WebSockets support is in the core](https://github.com/spring-projects/spring-framework/tree/master/spring-websocket/src/main/java/org/springframework/web/socket).

**Comment by michaelklishin** [comment]
@dumbbell someone from the Spring team suggests we should file this in [Spring JIRA](https://jira.spring.io/browse/SPR), for the WebSocket component.

**Comment by dumbbell** [comment]
Yeah, and I found at least a part of a [STOMP implementation in Spring Messaging](https://github.com/spring-projects/spring-framework/tree/master/spring-messaging/src/main/java/org/springframework/messaging/simp/stomp).

Ok, let's use their JIRA. Thanks!

**Comment by dumbbell** [comment]
Upstream issue: https://jira.spring.io/browse/SPR-13092

**Comment by rstoyanchev** [comment]
@samavedulark, based on the configuration you posted, you have a web application that's using Spring's WebSocket support (server-side) with STOMP as the sub-protocol. In this scenario the WebSocket server appears as the STOMP broker to clients (most likely browsers) providing validation, authentication, etc but ultimately relaying messages to and from RabbitMQ over TCP.

In short I expect Spring is merely forwarding ack/nack messages. What is the actual client used in the front end? stomp.js perhaps?

**Comment by rstoyanchev** [comment]
It seems stomp.js supports 1.1, 1.0 only. See http://jmesnil.net/stomp-websocket/doc/#protocols. It sends ACK/NACK frames that look like this: 

    ["ACK\nmessage-id:T_sub-2@@session-Zbgk6MMAf7hn2ZiufSATCA@@1\nsubscription:sub-2\n\n\u0000"]

...

    ["NACK\nrequeue:false\nmessage-id:T_sub-2@@session-hnCeWXZfq2Vmr0_YYPnXPw@@24\nsubscription:sub-2\n\n\u0000"]

**Comment by michaelklishin** [comment]
I've filed an issue with stomp-websocket: https://github.com/jmesnil/stomp-websocket/issues/111, thank you @rstoyanchev!

**Comment by rstoyanchev** [comment]
Good idea, stomp.js should have 1.2 support. 

That said @samavedulark could you confirm if you are indeed using stomp.js? The original comment shows "accept-version:1.2,1.1" which makes me think it could be some other client since [stomp.js is fixed|https://github.com/jmesnil/stomp-websocket/blob/master/src/stomp.coffee#L324] to send 1.1,1.0.

**Comment by samavedulark** [comment]
Sorry for late reply, we are using java client for sending stomp messages.
