### ISSUE TITLE
Two subscriptions using a single durable queue

### ISSUE THREAD

**Issue by laurentluce** [rabbitmq/rabbitmq-stomp#109]
Messages don't seem to end up on the right subscription when I have two subscriptions using a single durable queue.

Here is my routing configuration:

- One topic exchange: app
- Two STOMP subscriptions against that exchange using the same durable queue "queue-test"
  - topic.a.*
  - topic.b.*

rabbitmqctl list_bindings:

- exchange        queue-test  queue   queue-test  []
- app      exchange        queue-test  queue   topic.a.*   []
- app      exchange        queue-test  queue   topic.b.*   []

rabbitmqctl list_consumers:

- queue-test  <rabbit@localhost.2.20427.0>    T_sub.HNNZbjRINADxFbrp        true    0      []
- queue-test  <rabbit@localhost.2.20427.0>    T_sub.ApMOzTQPNUlvwhmj     true    0       []

rabbitmqctl list_queues:

- queue-test 0

Message 1 with destination topic.a.1 sent.
Message received on the right subscription:

```
MESSAGE
    subscription : sub.ApMOzTQPNUlvwhmj
    destination : /exchange/app/topic.a.1
    message-id : T_sub.ApMOzTQPNUlvwhmj@@session-uqt3ppLSTqUnYXQBPb4-6w@@1
    redelivered : false
    ack : T_sub.ApMOzTQPNUlvwhmj@@session-uqt3ppLSTqUnYXQBPb4-6w@@1
```

Message 2 with destination topic.a.1 sent.
Message received on the wrong subscription:

```
MESSAGE
    subscription : sub.HNNZbjRINADxFbrp
    destination : /exchange/app/topic.a.1
    message-id : T_sub.HNNZbjRINADxFbrp@@session-uqt3ppLSTqUnYXQBPb4-6w@@2
    redelivered : false
    ack : T_sub.HNNZbjRINADxFbrp@@session-uqt3ppLSTqUnYXQBPb4-6w@@2
```

Both messages should have been received on the subscription: ApMOzTQPNUlvwhmj since both messages destination match topic.a.* and not topic.b.*

**Comment by michaelklishin** [comment]
According to what you posted, both messages have the same destination and two consumers use a single queue.

When two consumers share a queue, a case known as competing consumers, messages are distributed in the round robin manner. See [tutorial two](http://www.rabbitmq.com/getstarted.html).

If you want both subscription to receive a copy, use a topic destination so that each has its own queue.

**Comment by michaelklishin** [comment]
In other words, message replication happens during the routing stage, not delivery. If you want N consumers to receive something, they must each have their own queue.

**Comment by laurentluce** [comment]
I don't want each subscription to receive a copy.  Each subscription above uses a different pattern:  `topic.a.*` and `topic.b.*`  I do use the same queue name when i send the STOMP subscribe commands.  I was expecting messages to be received based on the subscriptions topic pattern.  The message with destination `/exchange/app/topic.a.1` should not be received by the subscription with pattern `topic.b.*`

**Comment by michaelklishin** [comment]
@laurentluce see above. The feature you are asking for is known as consumer selectors. It is not available in RabbitMQ. Message distribution happens at the routing stage. I don't have anything to add to the comments above.

**Comment by michaelklishin** [comment]
To be more precise, consumer selectors are implemented in the jms-topic-exchange plugin but it is JMS-specific and doesn't fit the semantics of STOMP.

**Comment by laurentluce** [comment]
@michaelklishin  Thanks for clarifying.  I understand now that I need to use two queues.
