### ISSUE TITLE
Using term_to_binary to generate queue names is not forward-compatible

### ISSUE THREAD

**Issue by hairyhum** [rabbitmq/rabbitmq-stomp#115]
In OTP-20 `term_to_binary` has changed atom encoding without a way to generate older version.
`term_to_binary` hash is used in automatic queue name generation.
Although, queue name generation does not use atoms, so binaries generated in `20` are not different from `19.3`.

It still makes sense to not rely on `term_to_binary` hashes, because it can change in future versions.

The problem here is that it's used to generate queue names and renaming queues even in upgrade functions can be hard and cause bugs.
As an option, we can generate a binary, which will be the same as `term_to_binary` output.

**Comment by michaelklishin** [comment]
@hairyhum I vote for generating 19.3-compatible binaries (as we already did in at least one other place) and considering it for `3.6.x`.

**Comment by hairyhum** [comment]
Related to rabbitmq/rabbitmq-server#1243
