### ISSUE TITLE
Give names to temp_queues generated using reply-to header

### ISSUE THREAD

**Issue by rkchilaka** [rabbitmq/rabbitmq-stomp#135]
Thank you for using RabbitMQ and for taking the time to report an
issue.

## Does This Belong to GitHub or RabbitMQ Mailing List?

GIthub

I want to have temp-queues in rabbitmq with Rabbitmq-stomp over websockets plugin, I want to be able to give name to temp queues created by reply-to headers, this is forcing us to maintain an in memory map and clean this map up on losing the queues, which is very cumbersome, is there any way where we could give the name of the temp-queue that is created.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes that we have a certain amount of information to work with.

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing and sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. OS/systemd logs, [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html), deployment tool logs, etc

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have a complete enough understanding of what's going on, a recommendation will be provided or a new issues with more context will be filed.

Thank you.

**Comment by michaelklishin** [comment]
This plugin does not control queue names. I'm not sure what `reply-to` queues you are referring here but if you are trying to do what tutorial 6 demonstrates, it is entirely up to you what queue names you use. See what destinations are available [in the STOMP guide](https://www.rabbitmq.com/stomp.html#d.qd).

At the moment his doesn't have enough details and is mailing list material. Sorry.

**Comment by rkchilaka** [comment]
i am referring to the reply-to header in SEND frame of stomp. Temp Queue Destinations, it is mentioned that, inorder to create temporary queues, we should supply reply-to header. My question is how do we control the name of the temporary queue that is created.

**Comment by michaelklishin** [comment]
Accorindg to the code and one unit test, `/temp-queue/{queue}` should be supported as a value of said header. This discussion belongs to the mailing list. Consider providing a code example that can be used to understand what the end goal is.
