### ISSUE TITLE
Propagate x-queue-type when a queue is declared over STOMP

### ISSUE THREAD

**Issue by jrsamson** [rabbitmq/rabbitmq-stomp#138]
From https://www.rabbitmq.com/stomp.html#queue-parameters it seems that "x-queue-mode" is not supported. Its failing on queueDeclare. Can we please add it to the x-arguments.

**Comment by acogoluegnes** [comment]
@jrsamson I think you meant `x-queue-type`, to be able to use quorum queues with STOMP in 3.8?

If so, could you tell us more about your use case and the motivations to use quorum queues?

Quorum queues are meant to be "stable" resources (not coming and going), and STOMP registration may not have these exact semantics. There may be cases we haven't think of where quorum queues would be appropriate in the STOMP and the STOMP page could document them.

Thanks.

**Comment by michaelklishin** [comment]
The queues STOMP clients use can be durable and long-lived in nature. STOMP client should have the option of using quorum queues.
