### ISSUE TITLE
Cannot use hide_server_info via rabbitmq.conf

### ISSUE THREAD

**Issue by Mati24** [rabbitmq/rabbitmq-stomp#140]
* RabbitMQ version 3.7.18
* Erlang version 22.1-1
* RabbitMQ plugin information
```[E ] rabbitmq_management               3.7.18
[e ] rabbitmq_management_agent         3.7.18
[E ] rabbitmq_shovel                   3.7.18
[E ] rabbitmq_shovel_management        3.7.18
[E ] rabbitmq_stomp                    3.7.18
[e ] rabbitmq_web_dispatch             3.7.18
[E ] rabbitmq_web_stomp                3.7.18
```
* Operating system Debian 10.1

Hello,
I can't set the _hide_server_info_ option in config file since it uses the new config format. If I set 
`stomp.hide_server_info = true` in the rabbitmq.conf, I have this error :
`[error] You've tried to set stomp.hide_server_info, but there is no setting with that name.`
Maybe the option needs to be in priv/schema/rabbitmq_stomp.schema ?
Thank for your help

Reference to this option :
https://github.com/rabbitmq/rabbitmq-stomp/blob/000226a067e9397a7dedcc871c15572f37bf8562/src/rabbit_stomp_processor.erl#L609

**Comment by michaelklishin** [comment]
You are correct, it's missing from the schema. You have to use the `advanced.config` file for now.

**Comment by Mati24** [comment]
Ok thank you :+1:
