### ISSUE TITLE
Set redelivered header

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-stomp#21]
See [this thread](https://groups.google.com/forum/#!topic/rabbitmq-users/k-221hP-pTc). Note that Apollo sets `redelivered` to redelivery count.

We will likely use a boolean flag (just like in AMQP 0-9-1).

**Comment by priviterag** [comment]
should we split the issue and create a new one for redelivery count?

**Comment by michaelklishin** [comment]
@priviterag OK.
