### ISSUE TITLE
Declaring queues with arbitrary properties (e.g. auto_delete)

### ISSUE THREAD

**Issue by dwelch2344** [rabbitmq/rabbitmq-stomp#24]
We're using StompJS (with Spring Websockets providing broker access) to allow the browser to publish to exchanges and subscribe to queues. However, whenever we subscribe to a queue, the queue is created as `auto_delete = false` and no matter what we do we cannot seem to change that. However, if we subscribe to an exchange, we do get auto_delete exchanges created.

I've inspected the STOMP frames being created and verified there's no explicit setting whatsoever for `auto_delete`. I've inspected the StompJS source & haven't found anything that leads me to believe the library is responsible. I've also tried instrumenting the frames myself to include the setting (with keys of `auto_delete`, `autoDelete`, `auto-delete`, and pretty much anything else you can imagine) so I'm fairly confident I'm either doing something wrong or the "problem" (for lack of a better word) is on RabbitMQ's side. 

Could anyone provide me guidance on subscribing to auto_delete queues?

**Comment by michaelklishin** [comment]
Currently STOMP plugin assumes there are two cases: you either want a durable queue or an auto-deleted one.

Making this more flexible using STOMP headers is possible. Can you please be more specific about what you are trying to do?

**Comment by rstoyanchev** [comment]
In Spring we provide what we call "user destinations". They are conceptually similar to a "/temp-queue" except we generate a unique queue name based on the user's session id ([see here]((http://docs.spring.io/spring-framework/docs/current/spring-framework-reference/html/websocket.html#websocket-stomp-user-destination))). It allows any code in a web application to send a message to a user simply by knowing their user name. Making it easy to create auto-delete queues through headers would be very helpful, or some configuration option like [this in ActiveMQ](http://activemq.apache.org/delete-inactive-destinations.html) might be another alternative.

**Comment by michaelklishin** [comment]
I don't know if we will have enough time to finish this before `3.5.5`, so labelling for `3.6.0` to be on the safe side. This can go into 3.5.x.

**Comment by dwelch2344** [comment]
@rstoyanchev weighed in on a issue I opened! I'm probably more excited than I should be :smile: 

@michaelklishin Similar to Rossen's scenarios, we are essentially looking for "broadcast" queues that a user might join multiple times (one per browser window), or a group of users might join (based on their tenant in a multi-tenant system). 

Auto-Delete fits really well for this setup as a queue will be created when the first person requests it, allowing us to name the queues by tenant, user, date, etc. If we don't have that, we end up with a ton of queues (that currently are being cleaned up by policies, which can be tricky if one queue is particularly long lived) 

STOMP headers would be an absolutely awesome way to specify this, and possibly other attributes of the requested queue. 

Thanks!

**Comment by michaelklishin** [comment]
@dwelch2344 as of `3.6.0`, it will be possible to explicitly define properties for endpoints such as `/topic/` and `/queue` using subscription headers: `durable`, `auto-delete`, and `exclusive`, respectively.

**Comment by spatula75** [comment]
This is similar to something we need for a similar reason.  In our case, we configure permissions such that a user's queues must all start with the username followed by a $; for example, "foo$queuename", but we still use auto-delete queues that go away when the user disconnects (via AMQP).

Because the queues are auto-delete and not declared ahead of time, we're not able to use the subscribe /amq/queue/queuename paradigm, and because of autogenerated names, we also can't use the subscribe /exchange/name/routingkey paradigm (because permissions would fail).  And because most clients connect via AMQP but others must use Web-Stomp (for security/firewall reasons), we need the Stomp clients to be able to see the same AMQP exchanges as the AMQP clients.

If we could specify what we needed to specify using some header, be it an x-header or otherwise, we might have a great solution to our problem.

**Comment by priviterag** [comment]
@spatula75 Which exchange type are you publishing to? Do you publish directly to a named queue? If so, you might be able to subscribe using the /queue destination from your STOMP consumers.

BTW, please, post your question to rabbitmq-users@googlegroups.com You might find a larger audience and the solution would benefit the whole community. Thanks

**Comment by spatula75** [comment]
Posted a [much more detailed follow-up] (https://groups.google.com/forum/#!topic/rabbitmq-users/t9phDzQEP_Y) on the mailing list.

**Comment by rstoyanchev** [comment]
@michaelklishin what updates the stomp plugin page? https://www.rabbitmq.com/stomp.html. Should the changes here be refected there, in the Queue properties section probably?

**Comment by priviterag** [comment]
done: https://github.com/rabbitmq/rabbitmq-website/pull/91 <https://github.com/rabbitmq/rabbitmq-website/pull/91> it will be online for v3.5.7

**Comment by michaelklishin** [comment]
@rstoyanchev take a look at the [Branches section](https://github.com/rabbitmq/rabbitmq-website#branches). This particular feature will ship in 3.6.0, so it's not on the live site at the moment. We redeploy `next.rabbitmq.com` every so often.

**Comment by michaelklishin** [comment]
@priviterag you're talking about a different issue, this one won't be in `3.5.x`.

**Comment by rstoyanchev** [comment]
Thanks @priviterag and @michaelklishin.

**Comment by dwelch2344** [comment]
Just wanted to follow up with a major thank you. We'll be re-engineering our solution to use this in the next few weeks (and are VERY excited)

**Comment by michaelklishin** [comment]
We should look into using "persistent" as an alias for "durable" for [compatiblity reasons](https://groups.google.com/forum/#!topic/rabbitmq-users/FgfXSSs9-6Q).
