### ISSUE TITLE
nxdomain error on rabbit_stomp_test:test_direct_client_connections_are_not_leaked/0 running on OSX

### ISSUE THREAD

**Issue by priviterag** [rabbitmq/rabbitmq-stomp#31]
This test open 1000 STOMP connections. It's failing on default OSX because max open files is 256.

**Comment by michaelklishin** [comment]
100-150 should be sufficient for that test.

**Comment by priviterag** [comment]
@michaelklishin https://github.com/rabbitmq/rabbitmq-stomp/pull/33
