### ISSUE TITLE
Adding a newline char after the null char terminating each STOMP Frame creates problems

### ISSUE THREAD

**Issue by lars-ellebo** [rabbitmq/rabbitmq-stomp#38]
Starting from RabbitMQ version 3.5.4 you have started to add a newline char after the null char that terminates each STOMP Frame, so /0 has become /0/n.
This is creating huge problems for the thousands of embedded IoT devices we have connected to our RabbitMQ Cluster, and have been connected for years now using STOMP.
The firmware running in our devices are not able to handle this extra newline char which means that we are effectively not able to upgrade RabbitMQ beyond ver. 3.5.3.
Can I ask you to make this addition of a newline char configurable in the stomp section of the rabbitmq.config file in future versions of RabbitMQ, allowing us to configure whether we want the newline char added or not to the end of each STOMP Frame.
This will be a tremendous help to us.
Best Regards
Lars Ellebo
Schneider Electric

**Comment by videlalvaro** [comment]
For me this makes sense @michaelklishin

**Comment by michaelklishin** [comment]
There is no need to report the same thing [more than once](https://groups.google.com/forum/#!topic/rabbitmq-users/TGLg3ixAD8Y). This is not a RabbitMQ issue: you use a broken client.

Given that it's an embedded client where upgrading may or may not be possible, we will add a flag to make this optional but **this is not a RabbitMQ issue by any means**.

I will file a specific issue about this.

**Comment by michaelklishin** [comment]
@videlalvaro @lars-ellebo see https://github.com/rabbitmq/rabbitmq-stomp/pull/41. I'm not going to document the new option on purpose: people should be running in the spec-compliant mode, there is no excuse for not being compliant (other than "on device software is a giant pain to update") in this particular case.

It will be in `3.5.6`. We can produce a one off build earlier than that, ask on rabbitmq-users if you need it.
