### ISSUE TITLE
Hide server information header

### ISSUE THREAD

**Issue by sega-yarkin** [rabbitmq/rabbitmq-stomp#57]
When STOMP server accepts connection it sends information about software and version back to a user. We'd like to be able to have parameter to disable sending this information (for security reasons).

**Comment by michaelklishin** [comment]
This belongs to https://github.com/rabbitmq/rabbitmq-web-stomp.

**Comment by sega-yarkin** [comment]
@michaelklishin I though web-stomp is just adapter and anything from the stomp adapter is just bytes for it. I've found setting this header here - https://github.com/rabbitmq/rabbitmq-stomp/blob/master/src/rabbit_stomp_processor.erl#L546 - is it possible to change headers in web-stomp adapter?

**Comment by michaelklishin** [comment]
OK, I thought you meant the Cowboy header.

**Comment by sega-yarkin** [comment]
Thanks

**Comment by michaelklishin** [comment]
According to STOMP specs 1.0 through 1.2, the server header in `CONNECTED` frames is indeed [optional](https://stomp.github.io/stomp-specification-1.2.html#CONNECTED_Frame), so there is no reason to not do it.

**Comment by yixuan178** [comment]
hello, how to configure it in rabbitmq conf file to disable it? 
in nmap scan result, it will show:
5672/tcp  open  amqp         RabbitMQ 3.3.5 (0-9)
i want to disable version of RabbitMQ.

**Comment by michaelklishin** [comment]
As the milestone suggests the configuration setting was introduced in 3.6.2, so 3.3.5 cannot possibly have it. You have to [upgrade](http://www.rabbitmq.com/upgrade.html). Please direct questions to rabbitmq-users, our public mailing list, in the future.
