### ISSUE TITLE
Could not start rabbitmq-stomp

### ISSUE THREAD

**Issue by kalwar** [rabbitmq/rabbitmq-stomp#62]
Something weird thing going on with 61613 port I guess but even if I change my rabbitmq.config file it throws the same error.

I've tried changing the config file to

[
  {rabbitmq_stomp, [{tcp_listeners, [{"127.0.0.1", 61613},
                                     {"::1",       61613}]}]}
].

but still it throws the same error. 

Error description:
   {could_not_start,rabbitmq_stomp,
       {{undef,
            [{rabbit_networking,tcp_listener_spec,
                 [rabbit_stomp_listener_sup,
                  {{127,0,0,1},61613,inet},
                  [{backlog,128},{nodelay,true}],
                  ranch_tcp,rabbit_stomp_client_sup,
                  {stomp_configuration,"guest","guest",false,false},
                  stomp,"STOMP TCP Listener"],
                 []},
             {rabbit_stomp_sup,'-listener_specs/3-lc$^1/1-1-',4,
                 [{file,"src/rabbit_stomp_sup.erl"},{line,44}]},
             {rabbit_stomp_sup,init,1,
                 [{file,"src/rabbit_stomp_sup.erl"},{line,38}]},
             {supervisor,init,1,[{file,"supervisor.erl"},{line,272}]},
             {gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},
             {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,239}]}]},
        {rabbit_stomp,start,[normal,[]]}}}

**Comment by michaelklishin** [comment]
Questions belong to `rabbitmq-users`. `undef` means a module or function were not found — please mention how you built RabbitMQ when posting to the list.

**Comment by kalwar** [comment]
So do you mean that rabbitmq-stomp is not found or something else...
How do you fix this?

**Comment by michaelklishin** [comment]
@kalwar please ask questions on rabbitmq-users. Team RabbitMQ does not use GitHub issues for questions.

**Comment by kalwar** [comment]
Thanks. I'll be there.
