### ISSUE TITLE
Consider emitting stats for connections unconditionally

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-stomp#70]
This makes it much easier to reason about connection state/blocking via management UI and/or monitoring tools: we don't sacrifice accuracy.

The downside is that we emit a bit more stats when a lot of connections are blocked. But now that the new parallel event collector is merged, this sounds like a reasonable trade-off.

**Comment by hairyhum** [comment]
Fixed by #71
