### ISSUE TITLE
Standalone build fails with `behaviour ranch_protocol undefined`

### ISSUE THREAD

**Issue by michaesc** [rabbitmq/rabbitmq-stomp#90]
It seems there is a dependency to ranch that causes a standard plugin build to fail (in both rabbit-stomp and rabbit-mqtt) during build:

```
$ git clone https://github.com/rabbitmq/rabbitmq-stomp/rabbitmq-stomp.git && cd rabbitmq-stomp && make
[...]
...error is: compile: warnings being treated as errors21:33:31
src/rabbit_stomp_connection_sup.erl:20: behaviour ranch_protocol undefined21:33:41
erlang.mk:4971: recipe for target 'ebin/rabbitmq_stomp.app' failed21:33:59
make[1]: *** [ebin/rabbitmq_stomp.app] Error 1
```

**Comment by michaelklishin** [comment]
I don't think that's what's going on. Plugins do not declare dependency on Ranch because they declare a dependency on `rabbit`. The issue here is that warnings are treated as errors when they come from the project itself and not dependencies.

**Comment by michaelklishin** [comment]
And the reason for the discrepancy seems to be [explained in a comment](https://github.com/rabbitmq/rabbitmq-stomp/blob/master/rabbitmq-components.mk#L82).

**Comment by michaesc** [comment]
Your title 'standalone...' is better, thanks. I could also be wrong in my assumption that the correct way to build a plugin is to unpack sources and build independently from any rabbitmq-server sources.

The ranch version mismatch comment might not be relevant, but that comment is what led me to:

1. enter the 'ranch' dependency subdirectory
2. manually 'make' build the ranch dependency
3. continue building the (stomp|mqtt) plugin

...which works around the error in question. This was in version 3.6.3 as well as the trunk (last week.)

**Comment by lukebakken** [comment]
Now that all sources are in https://github.com/rabbitmq/rabbitmq-server, here is the process:

```
git clone https://github.com/rabbitmq/rabbitmq-server.git
cd rabbitmq-server/deps/rabbitmq_stomp
make DIST_AS_EZS=true dist
```
