### ISSUE TITLE
Override default exchange configuration

### ISSUE THREAD

**Issue by jkubrynski** [rabbitmq/rabbitmq-stomp#94]
Currently all STOMP messages are using amq.topic. It'll be great to be able to point them to configure STOMP plugin to use different exchange

**Comment by michaelklishin** [comment]
That's not really correct: you can use [any exchange with the right kind of destination](http://www.rabbitmq.com/stomp.html). I don't know if there's much value in configuring the exchange that's used "by default". So leaving this open with a "no-decision" label.

**Comment by jkubrynski** [comment]
@michaelklishin right, but this approach requires configuration changes on the application level. It'll be great to be able to override it in Rabbit

**Comment by michaelklishin** [comment]
@jkubrynski I still question how valuable that is. On the other hand it's a really small change so we will consider it.

**Comment by cardosso** [comment]
@michaelklishin So what was the decision? I think making this configurable makes sense.

**Comment by michaelklishin** [comment]
No objections to making this configurable.

**Comment by cardosso** [comment]
Nice, please make it happen :)

**Comment by michaelklishin** [comment]
This is open source software. Instead of asking others to make something happen you can do it yourself.

**Comment by cardosso** [comment]
If only rabbitmq wasn't coded in erlang... You said it that it was a really small change, for me I'd need to learn a new language, understand how the plugin works,  find out what exacty needs to be changed so not exactly a small task.
